language: ruby
cache: bundler
services:
- postgresql
before_script:
- psql -c 'create database demo_test;' -U postgres
rvm:
- 2.5.1
script:
- bundle install --jobs=3 --retry=3
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rspec
branches:
  only:
  - development
deploy:
  provider: heroku
  on:
    repo: ashishra0/last-fm-search
  api_key:
    secure: Wo2s/QSr3R5whbxvD3fz6yZR3e3cKhGUXOSL/6R59hGuzSbzSAK8rukf3Beq1f1Ng6aHHRka4KQzH57IDRL6dRivubVL/uPeLsbF5RMy2pudzv/5G9i0x4Ag9jg+xqVQCYYG4TN06aamV/n0hs4En+zZvCAJN+hmMbKDJvGmBO7XLHjB8ZQyHigvGi6wT3nUXusFcM1sCfgVtRltaqdRf8SScdtPipjxwZZefetQMsEV8EB3FnOAaGDJRF0IBu4dfaVaBX8zkQXuRpM29wD0zrOUkUYyWE6atYQN/m5yzVWZVtjhANhahn2wKpXnuMXu7LFbWKDtxjF5emBnLfFR+pegNoeqSO2Jz2fEGm/qqWlavZV0DwYYL8s6669dXsoqpdd2xkxYn9s86MRwRfSlWLSU6mpRT/sEDJ0EphRpprjbc7v3sMY1N3A6AjBYKx0Z+XBPtRI5iL93saFSag+WfKn3qhMxP7AGKi7kck06OwRCoFCKTfjrY0zqYo4urYDRnIfP+8OC0Gon8w5D3/wAbyF61AevlSdduQBbEYzBToQVN0axMB91qZtcVYPKQ/i1W5MNYQlA1tkJCew1tmrGTr/yNq0ia8rmdsGfRhZVoZAIqjD+iBMkPdhrR2oOFW3e1DN+LQc3k1KDQ4OT4lFcCtwKKXK6EQid/+O7PrG1uOc=
  app: last-fm-search
  run:
    - "rake db:migrate"
    - "restart"
    - "rake cleanup"
env:
  secure: Uc8r7l07Z+vSfpp5eQzEA24UfN5nUvqOBAWsYGVo60Yw0tit4KPgYw4DpVlk7RUwiqYl4/H+T4nyEs+pfoSXTkRd/LoLjeY9yzVklFNkRvRYoUV8kp0iKlOwcfSio2xa/GQ99V/shjPexz6WNnxNybQ4TcLeF6JXPmdnfzZCFNozLGw8RhOAco+G1TXqiVecf/EvPKK/i3UJL1uVn6rTRY91vrP2FTKD2Ecusr/98EOoMIi2sBOhZRs8FmrMVDFBt/QJkLIsSQ5hwZxbx4kMzLdxTDzZGJ7LJz3OB9yfPmz7zF13iTPJErBcDwDJnM1efMzPzxosMiB4TqA0qiByjHO6qmNGFXYxTQsaNXTTNrq6zgnlOt9uEUEDprIoiZXEwSJwxXGcURbgAtyHnbu4JsPyYruRpa6w3RwbcN+UMefhZQLKXpQoCwQwP2qnu5wdFZgyo+R5zaKNG/OhgZ1i4Nxga8jU5Q4ZodFzsgYKv4hAX+BAg7dTUobwgZWb93ZoYBivIqL5/bglhDQmtVmcYT5iw8nUrIFw4SWtQuRGwdbAjwvZJBCwlqAPowYWQsSDZUubl8NaBnk7oyrM5s5/bC/YmFkG71oIQ7jgW850u2MvxpQxG5l7jfnjI3BFgbpb6FhAGUicSNF2ESb5dCW70z9uroQ4DxzX+QvR84H6Ycs=
